# Generated by Django 5.0.6 on 2024-10-16 21:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                ("stake", models.FloatField()),
                ("stake_return", models.FloatField(blank=True, null=True)),
                (
                    "selection",
                    models.CharField(
                        choices=[("HEAD", "Head"), ("TAIL", "Tail")], max_length=10
                    ),
                ),
                (
                    "pc_selection",
                    models.CharField(
                        choices=[("HEAD", "Head"), ("TAIL", "Tail")], max_length=10
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[("won", "Won"), ("lost", "Lost"), ("na", "Na")],
                        default="na",
                        max_length=30,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="user_bet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now_add=True)),
                ("previous_bets", models.ManyToManyField(blank=True, to="core.bet")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="user_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
