# Generated by Django 5.0.6 on 2024-10-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="amount_won",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
